"""initial schema: base + admin cabinet entities

Revision ID: 1158b87c871d
Revises:
Create Date: 2026-07-06 16:51:57.473991
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

import src.infrastructure.database.base
from sqlalchemy.dialects import postgresql

revision: str = "1158b87c871d"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bot_config_values",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column(
            "value",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            src.infrastructure.database.base.AwareDateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            src.infrastructure.database.base.AwareDateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_bot_config_values_key"), "bot_config_values", ["key"], unique=True)
    op.create_table(
        "holidays",
        sa.Column("month", sa.Integer(), nullable=False),
        sa.Column("day", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "reward_type",
            sa.Enum(
                "DISCOUNT",
                "DAYS",
                "BALANCE",
                name="holidayrewardtype",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("value", sa.Integer(), nullable=False),
        sa.Column("send_time", sa.String(length=5), nullable=False),
        sa.Column(
            "results",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            src.infrastructure.database.base.AwareDateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            src.infrastructure.database.base.AwareDateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("month", "day", name="uq_holiday_date"),
    )
    op.create_table(
        "menu_nodes",
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(length=64), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "SCREEN",
                "ACTION",
                "LINK",
                "MINIAPP",
                "BACK",
                name="menunodekind",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("payload", sa.String(length=4096), nullable=True),
        sa.Column("custom_emoji_id", sa.String(length=32), nullable=True),
        sa.Column("color", sa.String(length=9), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            src.infrastructure.database.base.AwareDateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            src.infrastructure.database.base.AwareDateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["parent_id"], ["menu_nodes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_menu_nodes_parent_id"), "menu_nodes", ["parent_id"], unique=False)
    op.create_table(
        "miniapp_config",
        sa.Column("template", sa.String(length=32), nullable=False),
        sa.Column("title", sa.String(length=64), nullable=True),
        sa.Column("greeting", sa.String(length=256), nullable=True),
        sa.Column("accent_color", sa.String(length=9), nullable=True),
        sa.Column("photo_scale_pct", sa.Integer(), nullable=False),
        sa.Column("cover_path", sa.String(length=512), nullable=True),
        sa.Column(
            "published_at",
            src.infrastructure.database.base.AwareDateTime(timezone=True),
            nullable=True,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            src.infrastructure.database.base.AwareDateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            src.infrastructure.database.base.AwareDateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "payment_gateways",
        sa.Column(
            "type",
            sa.Enum(
                "MANUAL",
                "TELEGRAM_STARS",
                "YOOKASSA",
                "CRYPTOMUS",
                "CRYPTOBOT",
                "TRIBUTE",
                name="paymentgatewaytype",
                native_enum=False,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column(
            "currency",
            sa.Enum(
                "RUB", "USD", "EUR", "USDT", "XTR", name="currency", native_enum=False, length=8
            ),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("display_name", sa.String(length=64), nullable=True),
        sa.Column("fee_bp", sa.Integer(), nullable=False),
        sa.Column(
            "settings",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            src.infrastructure.database.base.AwareDateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            src.infrastructure.database.base.AwareDateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("type"),
    )
    op.create_table(
        "plans",
        sa.Column("public_code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.String(length=1024), nullable=True),
        sa.Column(
            "type",
            sa.Enum(
                "TRAFFIC",
                "DEVICES",
                "BOTH",
                "UNLIMITED",
                name="plantype",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column(
            "availability",
            sa.Enum(
                "ALL",
                "NEW",
                "EXISTING",
                "INVITED",
                "ALLOWED",
                "LINK",
                name="availability",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column(
            "traffic_limit_bytes",
            sa.BigInteger().with_variant(sa.BigInteger(), "sqlite"),
            nullable=True,
        ),
        sa.Column("device_limit", sa.Integer(), nullable=True),
        sa.Column("traffic_limit_strategy", sa.String(length=32), nullable=True),
        sa.Column(
            "allowed_telegram_ids",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "allowed_emails",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "internal_squads",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.Column("external_squad", sa.String(length=36), nullable=True),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_trial", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            src.infrastructure.database.base.AwareDateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            src.infrastructure.database.base.AwareDateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        sa.UniqueConstraint("public_code"),
    )
    op.create_table(
        "promo_groups",
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("server_discount_pct", sa.Integer(), nullable=False),
        sa.Column("traffic_discount_pct", sa.Integer(), nullable=False),
        sa.Column("device_discount_pct", sa.Integer(), nullable=False),
        sa.Column(
            "period_discounts",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "auto_assign_total_spent_minor",
            sa.BigInteger().with_variant(sa.BigInteger(), "sqlite"),
            nullable=True,
        ),
        sa.Column("apply_discounts_to_addons", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_promo_groups_priority"), "promo_groups", ["priority"], unique=False)
    op.create_table(
        "report_topics",
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column(
            "topic_id", sa.BigInteger().with_variant(sa.BigInteger(), "sqlite"), nullable=True
        ),
        sa.Column("schedule", sa.String(length=64), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            src.infrastructure.database.base.AwareDateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            src.infrastructure.database.base.AwareDateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "server_nodes",
        sa.Column("node_uuid", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("country_code", sa.String(length=8), nullable=True),
        sa.Column("address", sa.String(length=255), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "ONLINE",
                "MAINTENANCE",
                "OFFLINE",
                name="servernodestatus",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("users_online", sa.Integer(), nullable=False),
        sa.Column(
            "traffic_day_bytes",
            sa.BigInteger().with_variant(sa.BigInteger(), "sqlite"),
            nullable=False,
        ),
        sa.Column("load_pct", sa.Integer(), nullable=False),
        sa.Column("ping_ms", sa.Integer(), nullable=True),
        sa.Column("uptime_pct", sa.Integer(), nullable=True),
        sa.Column("is_for_sale", sa.Boolean(), nullable=False),
        sa.Column(
            "last_sync_at",
            src.infrastructure.database.base.AwareDateTime(timezone=True),
            nullable=True,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            src.infrastructure.database.base.AwareDateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            src.infrastructure.database.base.AwareDateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_server_nodes_node_uuid"), "server_nodes", ["node_uuid"], unique=True)
    op.create_table(
        "server_squads",
        sa.Column("squad_uuid", sa.Uuid(), nullable=False),
        sa.Column("display_name", sa.String(length=128), nullable=False),
        sa.Column("original_name", sa.String(length=128), nullable=True),
        sa.Column("country_code", sa.String(length=2), nullable=True),
        sa.Column("is_available", sa.Boolean(), nullable=False),
        sa.Column("is_trial_eligible", sa.Boolean(), nullable=False),
        sa.Column(
            "price_minor", sa.BigInteger().with_variant(sa.BigInteger(), "sqlite"), nullable=False
        ),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("max_users", sa.Integer(), nullable=True),
        sa.Column("current_users", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            src.infrastructure.database.base.AwareDateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            src.infrastructure.database.base.AwareDateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("squad_uuid"),
    )
    op.create_table(
        "settings",
        sa.Column(
            "default_currency",
            sa.Enum(
                "RUB", "USD", "EUR", "USDT", "XTR", name="currency", native_enum=False, length=8
            ),
            nullable=False,
        ),
        sa.Column(
            "access",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "requirements",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "notifications",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "referral",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "backup",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "blacklist",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "menu",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "smart_reminder",
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("days_before", sa.String(length=32), nullable=False),
        sa.Column("send_time", sa.String(length=5), nullable=False),
        sa.Column("text", sa.String(length=4096), nullable=False),
        sa.Column("button_enabled", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            src.infrastructure.database.base.AwareDateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            src.infrastructure.database.base.AwareDateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "campaigns",
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("start_param", sa.String(length=64), nullable=False),
        sa.Column("promo_group_id", sa.Integer(), nullable=True),
        sa.Column(
            "cost_minor", sa.BigInteger().with_variant(sa.BigInteger(), "sqlite"), nullable=False
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            src.infrastructure.database.base.AwareDateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            src.infrastructure.database.base.AwareDateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["promo_group_id"], ["promo_groups.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_campaigns_start_param"), "campaigns", ["start_param"], unique=True)
    op.create_table(
        "plan_durations",
        sa.Column("plan_id", sa.Integer(), nullable=False),
        sa.Column("days", sa.Integer(), nullable=False),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["plan_id"], ["plans.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_plan_durations_plan_id"), "plan_durations", ["plan_id"], unique=False)
    op.create_table(
        "promocodes",
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "reward_type",
            sa.Enum(
                "BALANCE",
                "DURATION",
                "TRAFFIC",
                "DEVICES",
                "SUBSCRIPTION",
                "PROMO_GROUP",
                "PERSONAL_DISCOUNT",
                "PURCHASE_DISCOUNT",
                name="rewardtype",
                native_enum=False,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column("reward_value", sa.Integer(), nullable=False),
        sa.Column(
            "plan_snapshot",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=True,
        ),
        sa.Column("promo_group_id", sa.Integer(), nullable=True),
        sa.Column(
            "availability",
            sa.Enum(
                "ALL",
                "NEW",
                "EXISTING",
                "INVITED",
                "ALLOWED",
                "LINK",
                name="availability",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("first_purchase_only", sa.Boolean(), nullable=False),
        sa.Column(
            "expires_at",
            src.infrastructure.database.base.AwareDateTime(timezone=True),
            nullable=True,
        ),
        sa.Column("max_activations", sa.Integer(), nullable=True),
        sa.Column("is_reusable", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            src.infrastructure.database.base.AwareDateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            src.infrastructure.database.base.AwareDateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["promo_group_id"], ["promo_groups.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_promocodes_code"), "promocodes", ["code"], unique=True)
    op.create_table(
        "plan_prices",
        sa.Column("plan_duration_id", sa.Integer(), nullable=False),
        sa.Column(
            "currency",
            sa.Enum(
                "RUB", "USD", "EUR", "USDT", "XTR", name="currency", native_enum=False, length=8
            ),
            nullable=False,
        ),
        sa.Column(
            "price_minor", sa.BigInteger().with_variant(sa.BigInteger(), "sqlite"), nullable=False
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["plan_duration_id"], ["plan_durations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_plan_prices_plan_duration_id"), "plan_prices", ["plan_duration_id"], unique=False
    )
    op.create_table(
        "users",
        sa.Column(
            "telegram_id", sa.BigInteger().with_variant(sa.BigInteger(), "sqlite"), nullable=True
        ),
        sa.Column(
            "auth_type",
            sa.Enum("TELEGRAM", "EMAIL", "OAUTH", name="authtype", native_enum=False, length=16),
            nullable=False,
        ),
        sa.Column("username", sa.String(length=64), nullable=True),
        sa.Column("first_name", sa.String(length=128), nullable=True),
        sa.Column("last_name", sa.String(length=128), nullable=True),
        sa.Column(
            "language",
            sa.Enum("EN", "RU", name="locale", native_enum=False, length=8),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "BLOCKED", name="userstatus", native_enum=False, length=16),
            nullable=False,
        ),
        sa.Column(
            "role",
            sa.Enum("USER", "PREVIEW", "ADMIN", "DEV", "OWNER", "SYSTEM", name="role"),
            nullable=False,
        ),
        sa.Column(
            "balance_minor", sa.BigInteger().with_variant(sa.BigInteger(), "sqlite"), nullable=False
        ),
        sa.Column(
            "currency",
            sa.Enum(
                "RUB", "USD", "EUR", "USDT", "XTR", name="currency", native_enum=False, length=8
            ),
            nullable=False,
        ),
        sa.Column("referral_code", sa.String(length=16), nullable=False),
        sa.Column("referred_by_id", sa.Integer(), nullable=True),
        sa.Column("referral_commission_percent", sa.Integer(), nullable=True),
        sa.Column("campaign_id", sa.Integer(), nullable=True),
        sa.Column("personal_discount_pct", sa.Integer(), nullable=False),
        sa.Column("purchase_discount_pct", sa.Integer(), nullable=False),
        sa.Column("is_trial_available", sa.Boolean(), nullable=False),
        sa.Column("has_had_paid_subscription", sa.Boolean(), nullable=False),
        sa.Column("has_made_first_topup", sa.Boolean(), nullable=False),
        sa.Column("is_rules_accepted", sa.Boolean(), nullable=False),
        sa.Column("current_subscription_id", sa.Integer(), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("email_verified", sa.Boolean(), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column(
            "notification_settings",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            src.infrastructure.database.base.AwareDateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            src.infrastructure.database.base.AwareDateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["campaign_id"], ["campaigns.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["referred_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_campaign_id"), "users", ["campaign_id"], unique=False)
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=False)
    op.create_index("ix_users_referral_code", "users", ["referral_code"], unique=True)
    op.create_index(op.f("ix_users_telegram_id"), "users", ["telegram_id"], unique=True)
    op.create_table(
        "audit_log",
        sa.Column("actor_user_id", sa.Integer(), nullable=True),
        sa.Column("actor_label", sa.String(length=64), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("entity", sa.String(length=64), nullable=True),
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            src.infrastructure.database.base.AwareDateTime(timezone=True),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["actor_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_log_action"), "audit_log", ["action"], unique=False)
    op.create_index(op.f("ix_audit_log_created_at"), "audit_log", ["created_at"], unique=False)
    op.create_table(
        "broadcasts",
        sa.Column(
            "audience",
            sa.Enum(
                "ALL",
                "ACTIVE",
                "TRIAL",
                "EXPIRED",
                name="broadcastaudience",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column(
            "media",
            sa.Enum("TEXT", "PHOTO", "VIDEO", name="broadcastmedia", native_enum=False, length=16),
            nullable=False,
        ),
        sa.Column("text", sa.String(length=4096), nullable=False),
        sa.Column("media_path", sa.String(length=512), nullable=True),
        sa.Column("button_enabled", sa.Boolean(), nullable=False),
        sa.Column("button_text", sa.String(length=64), nullable=True),
        sa.Column("button_url", sa.String(length=512), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "RUNNING",
                "DONE",
                "FAILED",
                "CANCELED",
                name="broadcaststatus",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("total", sa.Integer(), nullable=False),
        sa.Column("sent", sa.Integer(), nullable=False),
        sa.Column("failed", sa.Integer(), nullable=False),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.Column(
            "started_at",
            src.infrastructure.database.base.AwareDateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "finished_at",
            src.infrastructure.database.base.AwareDateTime(timezone=True),
            nullable=True,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            src.infrastructure.database.base.AwareDateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            src.infrastructure.database.base.AwareDateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_broadcasts_status"), "broadcasts", ["status"], unique=False)
    op.create_table(
        "promocode_activations",
        sa.Column("promocode_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "activated_at",
            src.infrastructure.database.base.AwareDateTime(timezone=True),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["promocode_id"], ["promocodes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_promocode_activations_promocode_id"),
        "promocode_activations",
        ["promocode_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_promocode_activations_user_id"), "promocode_activations", ["user_id"], unique=False
    )
    op.create_index(
        "uq_promo_user", "promocode_activations", ["promocode_id", "user_id"], unique=True
    )
    op.create_table(
        "referrals",
        sa.Column("referrer_id", sa.Integer(), nullable=False),
        sa.Column("referred_id", sa.Integer(), nullable=False),
        sa.Column("level", sa.Enum("FIRST", "SECOND", name="referrallevel"), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            src.infrastructure.database.base.AwareDateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            src.infrastructure.database.base.AwareDateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["referred_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["referrer_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("referred_id"),
    )
    op.create_index(op.f("ix_referrals_referrer_id"), "referrals", ["referrer_id"], unique=False)
    op.create_table(
        "subscriptions",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("remnawave_uuid", sa.Uuid(), nullable=True),
        sa.Column("short_id", sa.String(length=16), nullable=False),
        sa.Column("plan_id", sa.Integer(), nullable=True),
        sa.Column(
            "plan_snapshot",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "TRIAL",
                "ACTIVE",
                "LIMITED",
                "EXPIRED",
                "DISABLED",
                "PENDING",
                "DELETED",
                name="subscriptionstatus",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("is_trial", sa.Boolean(), nullable=False),
        sa.Column("disabled_by_channel_leave", sa.Boolean(), nullable=False),
        sa.Column(
            "traffic_limit_bytes",
            sa.BigInteger().with_variant(sa.BigInteger(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "traffic_used_bytes",
            sa.BigInteger().with_variant(sa.BigInteger(), "sqlite"),
            nullable=False,
        ),
        sa.Column("device_limit", sa.Integer(), nullable=True),
        sa.Column("traffic_limit_strategy", sa.String(length=32), nullable=True),
        sa.Column(
            "internal_squads",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.Column("external_squad", sa.String(length=36), nullable=True),
        sa.Column(
            "start_at", src.infrastructure.database.base.AwareDateTime(timezone=True), nullable=True
        ),
        sa.Column(
            "expire_at",
            src.infrastructure.database.base.AwareDateTime(timezone=True),
            nullable=True,
        ),
        sa.Column("subscription_url", sa.String(length=512), nullable=True),
        sa.Column("crypto_link", sa.String(length=512), nullable=True),
        sa.Column("autopay_enabled", sa.Boolean(), nullable=False),
        sa.Column("autopay_days_before", sa.Integer(), nullable=False),
        sa.Column("autopay_period_days", sa.Integer(), nullable=True),
        sa.Column(
            "device_reset_at",
            src.infrastructure.database.base.AwareDateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "link_reset_at",
            src.infrastructure.database.base.AwareDateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "last_webhook_at",
            src.infrastructure.database.base.AwareDateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "last_revoke_at",
            src.infrastructure.database.base.AwareDateTime(timezone=True),
            nullable=True,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            src.infrastructure.database.base.AwareDateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            src.infrastructure.database.base.AwareDateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["plan_id"], ["plans.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("short_id"),
    )
    op.create_index(
        op.f("ix_subscriptions_expire_at"), "subscriptions", ["expire_at"], unique=False
    )
    op.create_index(op.f("ix_subscriptions_status"), "subscriptions", ["status"], unique=False)
    op.create_index(op.f("ix_subscriptions_user_id"), "subscriptions", ["user_id"], unique=False)
    op.create_index(
        "uq_active_sub",
        "subscriptions",
        ["user_id", "plan_id"],
        unique=True,
        postgresql_where=sa.text("status IN ('ACTIVE', 'TRIAL', 'LIMITED')"),
        sqlite_where=sa.text("status IN ('ACTIVE', 'TRIAL', 'LIMITED')"),
    )
    op.create_table(
        "tickets",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("subject", sa.String(length=256), nullable=False),
        sa.Column(
            "status",
            sa.Enum("OPEN", "WAITING", "CLOSED", name="ticketstatus", native_enum=False, length=16),
            nullable=False,
        ),
        sa.Column(
            "closed_at",
            src.infrastructure.database.base.AwareDateTime(timezone=True),
            nullable=True,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            src.infrastructure.database.base.AwareDateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            src.infrastructure.database.base.AwareDateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tickets_status"), "tickets", ["status"], unique=False)
    op.create_index(op.f("ix_tickets_user_id"), "tickets", ["user_id"], unique=False)
    op.create_table(
        "transactions",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "DEPOSIT",
                "WITHDRAWAL",
                "SUBSCRIPTION_PAYMENT",
                "REFUND",
                "REFERRAL_REWARD",
                "GIFT",
                name="transactiontype",
                native_enum=False,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column("payment_id", sa.Uuid(), nullable=False),
        sa.Column("external_id", sa.String(length=128), nullable=True),
        sa.Column(
            "gateway_type",
            sa.Enum(
                "MANUAL",
                "TELEGRAM_STARS",
                "YOOKASSA",
                "CRYPTOMUS",
                "CRYPTOBOT",
                "TRIBUTE",
                name="paymentgatewaytype",
                native_enum=False,
                length=24,
            ),
            nullable=True,
        ),
        sa.Column("gateway_display_name", sa.String(length=64), nullable=True),
        sa.Column("payment_method", sa.String(length=64), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "COMPLETED",
                "CANCELED",
                "REFUNDED",
                "FAILED",
                name="transactionstatus",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column(
            "amount_minor", sa.BigInteger().with_variant(sa.BigInteger(), "sqlite"), nullable=False
        ),
        sa.Column(
            "currency",
            sa.Enum(
                "RUB", "USD", "EUR", "USDT", "XTR", name="currency", native_enum=False, length=8
            ),
            nullable=False,
        ),
        sa.Column(
            "pricing",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=False,
        ),
        sa.Column(
            "plan_snapshot",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=True,
        ),
        sa.Column(
            "purchase_type",
            sa.Enum("NEW", "RENEW", "CHANGE", name="purchasetype", native_enum=False, length=16),
            nullable=True,
        ),
        sa.Column("is_test", sa.Boolean(), nullable=False),
        sa.Column("receipt_uuid", sa.String(length=64), nullable=True),
        sa.Column(
            "receipt_created_at",
            src.infrastructure.database.base.AwareDateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "completed_at",
            src.infrastructure.database.base.AwareDateTime(timezone=True),
            nullable=True,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            src.infrastructure.database.base.AwareDateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            src.infrastructure.database.base.AwareDateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("payment_id"),
    )
    op.create_index(op.f("ix_transactions_status"), "transactions", ["status"], unique=False)
    op.create_index(op.f("ix_transactions_user_id"), "transactions", ["user_id"], unique=False)
    op.create_index(
        "uq_external_gateway", "transactions", ["external_id", "gateway_type"], unique=True
    )
    op.create_table(
        "user_promo_groups",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("promo_group_id", sa.Integer(), nullable=False),
        sa.Column(
            "assigned_at",
            src.infrastructure.database.base.AwareDateTime(timezone=True),
            nullable=False,
        ),
        sa.Column("assigned_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["promo_group_id"], ["promo_groups.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "promo_group_id"),
    )
    op.create_table(
        "referral_earnings",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("referral_id", sa.Integer(), nullable=False),
        sa.Column(
            "amount_minor", sa.BigInteger().with_variant(sa.BigInteger(), "sqlite"), nullable=False
        ),
        sa.Column("reason", sa.String(length=64), nullable=True),
        sa.Column("transaction_id", sa.Integer(), nullable=True),
        sa.Column("is_issued", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            src.infrastructure.database.base.AwareDateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            src.infrastructure.database.base.AwareDateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["referral_id"], ["referrals.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["transaction_id"], ["transactions.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_referral_earnings_user_id"), "referral_earnings", ["user_id"], unique=False
    )
    op.create_table(
        "ticket_messages",
        sa.Column("ticket_id", sa.Integer(), nullable=False),
        sa.Column(
            "author",
            sa.Enum("USER", "ADMIN", name="ticketauthor", native_enum=False, length=8),
            nullable=False,
        ),
        sa.Column("text", sa.String(length=4096), nullable=False),
        sa.Column(
            "created_at",
            src.infrastructure.database.base.AwareDateTime(timezone=True),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["ticket_id"], ["tickets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ticket_messages_ticket_id"), "ticket_messages", ["ticket_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ticket_messages_ticket_id"), table_name="ticket_messages")
    op.drop_table("ticket_messages")
    op.drop_index(op.f("ix_referral_earnings_user_id"), table_name="referral_earnings")
    op.drop_table("referral_earnings")
    op.drop_table("user_promo_groups")
    op.drop_index("uq_external_gateway", table_name="transactions")
    op.drop_index(op.f("ix_transactions_user_id"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_status"), table_name="transactions")
    op.drop_table("transactions")
    op.drop_index(op.f("ix_tickets_user_id"), table_name="tickets")
    op.drop_index(op.f("ix_tickets_status"), table_name="tickets")
    op.drop_table("tickets")
    op.drop_index(
        "uq_active_sub",
        table_name="subscriptions",
        postgresql_where=sa.text("status IN ('ACTIVE', 'TRIAL', 'LIMITED')"),
        sqlite_where=sa.text("status IN ('ACTIVE', 'TRIAL', 'LIMITED')"),
    )
    op.drop_index(op.f("ix_subscriptions_user_id"), table_name="subscriptions")
    op.drop_index(op.f("ix_subscriptions_status"), table_name="subscriptions")
    op.drop_index(op.f("ix_subscriptions_expire_at"), table_name="subscriptions")
    op.drop_table("subscriptions")
    op.drop_index(op.f("ix_referrals_referrer_id"), table_name="referrals")
    op.drop_table("referrals")
    op.drop_index("uq_promo_user", table_name="promocode_activations")
    op.drop_index(op.f("ix_promocode_activations_user_id"), table_name="promocode_activations")
    op.drop_index(op.f("ix_promocode_activations_promocode_id"), table_name="promocode_activations")
    op.drop_table("promocode_activations")
    op.drop_index(op.f("ix_broadcasts_status"), table_name="broadcasts")
    op.drop_table("broadcasts")
    op.drop_index(op.f("ix_audit_log_created_at"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_action"), table_name="audit_log")
    op.drop_table("audit_log")
    op.drop_index(op.f("ix_users_telegram_id"), table_name="users")
    op.drop_index("ix_users_referral_code", table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index(op.f("ix_users_campaign_id"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_plan_prices_plan_duration_id"), table_name="plan_prices")
    op.drop_table("plan_prices")
    op.drop_index(op.f("ix_promocodes_code"), table_name="promocodes")
    op.drop_table("promocodes")
    op.drop_index(op.f("ix_plan_durations_plan_id"), table_name="plan_durations")
    op.drop_table("plan_durations")
    op.drop_index(op.f("ix_campaigns_start_param"), table_name="campaigns")
    op.drop_table("campaigns")
    op.drop_table("smart_reminder")
    op.drop_table("settings")
    op.drop_table("server_squads")
    op.drop_index(op.f("ix_server_nodes_node_uuid"), table_name="server_nodes")
    op.drop_table("server_nodes")
    op.drop_table("report_topics")
    op.drop_index(op.f("ix_promo_groups_priority"), table_name="promo_groups")
    op.drop_table("promo_groups")
    op.drop_table("plans")
    op.drop_table("payment_gateways")
    op.drop_table("miniapp_config")
    op.drop_index(op.f("ix_menu_nodes_parent_id"), table_name="menu_nodes")
    op.drop_table("menu_nodes")
    op.drop_table("holidays")
    op.drop_index(op.f("ix_bot_config_values_key"), table_name="bot_config_values")
    op.drop_table("bot_config_values")
    # ### end Alembic commands ###
