"""constructor periods and traffic packs

Revision ID: 3c3a765fca32
Revises: 1158b87c871d
Create Date: 2026-07-06 16:56:57.858965
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

import src.infrastructure.database.base


revision: str = "3c3a765fca32"
down_revision: str | None = "1158b87c871d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "constructor_periods",
        sa.Column("days", sa.Integer(), nullable=False),
        sa.Column(
            "price_minor", sa.BigInteger().with_variant(sa.BigInteger(), "sqlite"), nullable=False
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            src.infrastructure.database.base.AwareDateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            src.infrastructure.database.base.AwareDateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("days"),
    )
    op.create_table(
        "traffic_packs",
        sa.Column("gb", sa.Integer(), nullable=False),
        sa.Column(
            "price_minor", sa.BigInteger().with_variant(sa.BigInteger(), "sqlite"), nullable=False
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            src.infrastructure.database.base.AwareDateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            src.infrastructure.database.base.AwareDateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("gb"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("traffic_packs")
    op.drop_table("constructor_periods")
    # ### end Alembic commands ###
